#dict to write the company names rigth

dict_company_names_long = {
    "adidas": "Adidas",
    "airbus": "Airbus",
    "allianz": "Allianz",
    "basf": "BASF",
    "bayer": "Bayer",
    "bmw": "BMW St",
    "brenntag": "Brenntag",
    "continental": "Continental",
    "covestro": "Covestro",
    "daimler_truck": "Daimler Truck",
    "delivery_hero": "Delivery Hero",
    "deutsche_bank": "Deutsche Bank",
    "deutsche_boerse": "Deutsche Börse",
    "deutsche_post": "Deutsche Post",
    "deutsche_telekom": "Deutsche Telekom",
    "eon": "E.ON",
    "fresenius": "Fresenius",
    "fresenius_medical_care": "Fresenius Medical Care",
    "hannover_rueck": "Hannover Rück",
    "heidelbergcement": "HeidelbergCement",
    "hellofresh": "HelloFresh",
    "henkel_vz": "Henkel Vz",
    "infineon": "Infineon",
    "linde": "Linde PLC",
    "mercedes-benz": "Mercedes-Benz Group (ex Daimler)",
    "merck": "Merck KGaA",
    "mtu": "MTU Aero Engines",
    "munich_re": "Münchener Rück",
    "porsche": "Porsche Vz",
    "puma": "Puma",
    "qiagen": "Qiagen",
    "rwe": "RWE",
    "sap": "SAP",
    "sartorius_vz": "Sartorius Vz",
    "siemens": "Siemens",
    "siemens_healthineers": "Siemens Healthineers",
    "symrise": "Symrise",
    "volkswagen": "Volkswagen Vz",
    "vonovia": "Vonovia",
    "zalando": "Zalando",
}

dict_company_names = {
    "basf": "BASF",
    "bmw": "BMW",
    "eon": "E.ON",
    "henkel_vz": "Henkel vz.",
    "mtu": "MTU",
    "munich_re": "Munich RE",
    "qiagen": "OIAGEN",
    "rwe": "RWE",
    "sap": "SAP",
    "sartorius_vz": "Sartorius vz.",
    'hellofresh': 'HelloFresh'
}
